spring:
  freemarker:
    expose-request-attributes: true

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

mail:
  properties:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

image:
  dir: "C:/Users/kormi/Pictures/java"

